FROM nginx:alpine

RUN mkdir -p /usr/src/app/static
WORKDIR /usr/src/app/static
COPY ./static .
RUN mkdir -p /usr/src/app/media
WORKDIR /usr/src/app/media
COPY ./media .
COPY ./cicd/docker-compose/nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/src/app/
